-- Pick your DB
USE [advsql];  -- <- change if needed
GO

BEGIN TRY
  BEGIN TRAN;

  -- Children first
  DELETE FROM dbo.APP_BINTRANSACTION;
  DELETE FROM dbo.APP_ALERT;
  DELETE FROM dbo.APP_ASSEMBLY;

  -- Then bins and people
  DELETE FROM dbo.APP_BIN;
  DELETE FROM dbo.APP_WORKER;

  -- Masters (but keep CONFIG)
  DELETE FROM dbo.APP_STATION;
  DELETE FROM dbo.APP_PART;
  -- DO NOT: DELETE FROM dbo.APP_CONFIG;

  -- Reset identities (next insert starts at 1)
  DBCC CHECKIDENT ('dbo.APP_BINTRANSACTION', RESEED, 0);
  DBCC CHECKIDENT ('dbo.APP_ALERT',          RESEED, 0);
  DBCC CHECKIDENT ('dbo.APP_ASSEMBLY',       RESEED, 0);
  DBCC CHECKIDENT ('dbo.APP_BIN',            RESEED, 0);
  DBCC CHECKIDENT ('dbo.APP_WORKER',         RESEED, 0);
  DBCC CHECKIDENT ('dbo.APP_STATION',        RESEED, 0);
  DBCC CHECKIDENT ('dbo.APP_PART',           RESEED, 0);

  COMMIT TRAN;
END TRY
BEGIN CATCH
  IF XACT_STATE() <> 0 ROLLBACK TRAN;
  THROW;
END CATCH;
GO

-- Sanity check
SELECT 'APP_BINTRANSACTION' tbl, COUNT(*) cnt FROM dbo.APP_BINTRANSACTION UNION ALL
SELECT 'APP_ALERT',          COUNT(*)     FROM dbo.APP_ALERT UNION ALL
SELECT 'APP_ASSEMBLY',       COUNT(*)     FROM dbo.APP_ASSEMBLY UNION ALL
SELECT 'APP_BIN',            COUNT(*)     FROM dbo.APP_BIN UNION ALL
SELECT 'APP_WORKER',         COUNT(*)     FROM dbo.APP_WORKER UNION ALL
SELECT 'APP_STATION',        COUNT(*)     FROM dbo.APP_STATION UNION ALL
SELECT 'APP_PART',           COUNT(*)     FROM dbo.APP_PART UNION ALL
SELECT 'APP_CONFIG (kept)',  COUNT(*)     FROM dbo.APP_CONFIG;

